version: '3.9'

networks:
  domjudge:
    name: domjudge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    networks:
      - domjudge
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    # 【学習済】mysqldを削除し、パケットサイズ拡張とバージョン対策オプションを追加済み
    command: --max-allowed-packet=128M --innodb-log-file-size=2G --innodb-snapshot-isolation=OFF

  domserver:
    container_name: domserver
    image: domjudge/domserver:latest
    # Domserverは読み取り専用(:ro)のままでOK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge
    ports:
      - 12345:80
    depends_on:
      - mariadb
    environment:
      - CONTAINER_TIMEZONE=Asia/Tokyo
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge

  # Judgehostの設定（4台分）
  judgehost-0:
    container_name: judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    # 【学習済】書き込み権限(:rw)に変更済み
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=0
      # ↓このパスワードは仮置きです。起動後に書き換えます。
      - JUDGEDAEMON_PASSWORD=I3J5MZyLNfJ68gXMAIPRKHxpXQ77xtic

  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=1
      - JUDGEDAEMON_PASSWORD=I3J5MZyLNfJ68gXMAIPRKHxpXQ77xtic

  judgehost-2:
    container_name: judgehost-2
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=2
      - JUDGEDAEMON_PASSWORD=I3J5MZyLNfJ68gXMAIPRKHxpXQ77xtic

  judgehost-3:
    container_name: judgehost-3
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - DAEMON_ID=3
      - JUDGEDAEMON_PASSWORD=I3J5MZyLNfJ68gXMAIPRKHxpXQ77xtic